### ISSUE TITLE
您好  demo在最新的CCC里面contentadapter失效

### ISSUE THREAD

**Issue by lucasbozhi** [zhitaocai/CocosCreator-Multi-resolution-Adapter#1]
![image](https://user-images.githubusercontent.com/10824207/56690793-e6278c80-6710-11e9-9c0d-a1f4eb74942d.png)
ccc.2.1.0

![image](https://user-images.githubusercontent.com/10824207/56690856-0e16f000-6711-11e9-88eb-a4a00f03b62a.png)
两边的widget丢失  未对代码做任何修改

**Comment by zhitaocai** [comment]
还没有对 2.1.x 版本做验证适配呢，后续在适配看看~

**Comment by lucasbozhi** [comment]
没问题，要刷新下 ... 不过现在有个新问题能请教下吗？
一个content已经用来你的适配脚本，然后有一个scrollview ，里面挂widget 左对齐，下级view也设置了widget左对齐  view有固定宽度，现在需要在不同的手机上动态设置view的宽度，写了一套动态的算法，但是执行的时机不对，需要在你的脚本 和 widget执行自动适配后 再进行我的算法计算才行 我的脚本是进行宽度计算和重新定位position，  调试的时候发现，在view的onload期间的position和加载完成后 view组件的postion都不相同... 想问一下    您的脚本如何结合scrollview使用
