### ISSUE TITLE
函数报错

### ISSUE THREAD

**Issue by Lichangzhong123** [zhitaocai/CocosCreator-Multi-resolution-Adapter#3]
cc.view.getCanvasSize().好像已经没有了

**Comment by zhitaocai** [comment]
你是在哪个版本发现没有呢？

我在ccc 2.0.2、2.0.5、2.0.8、2.0.9、2.0.10、2.1.1 上都发现还可以使用

**Comment by Lichangzhong123** [comment]
在官方API也没有找到



------------------ 原始邮件 ------------------
发件人: "Zhitao Cai"<notifications@github.com>; 
发送时间: 2019年6月24日(星期一) 晚上6:51
收件人: "zhitaocai/CocosCreator-Multi-resolution-Adapter"<CocosCreator-Multi-resolution-Adapter@noreply.github.com>; 
抄送: "鉨、若尘封"<492199156@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhitaocai/CocosCreator-Multi-resolution-Adapter] 函数报错 (#3)




你是在哪个版本发现没有呢？
 
我在ccc 2.0.2、2.0.5、2.0.8、2.0.9、2.0.10、2.1.1 上都发现还可以使用

**Comment by Lichangzhong123** [comment]
1.9.1




------------------ 原始邮件 ------------------
发件人: "Zhitao Cai"<notifications@github.com>; 
发送时间: 2019年6月24日(星期一) 晚上6:51
收件人: "zhitaocai/CocosCreator-Multi-resolution-Adapter"<CocosCreator-Multi-resolution-Adapter@noreply.github.com>; 
抄送: "鉨、若尘封"<492199156@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhitaocai/CocosCreator-Multi-resolution-Adapter] 函数报错 (#3)




你是在哪个版本发现没有呢？
 
我在ccc 2.0.2、2.0.5、2.0.8、2.0.9、2.0.10、2.1.1 上都发现还可以使用

**Comment by zhitaocai** [comment]
![image](https://user-images.githubusercontent.com/5856724/60062502-11882100-972c-11e9-831d-412cbf47e5bf.png)

本项目不支持 Cocos Creator 1.x
